name: Test UnrealIRCd Module

on:
  push:
    branches:
      - main
      - 'feature/*'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libcurl4-openssl-dev libjansson-dev pkg-config

    - name: Download and Install UnrealIRCd
      run: |
        wget https://www.unrealircd.org/downloads/unrealircd-latest.tar.gz
        tar zxvf unrealircd-latest.tar.gz
        cd unrealircd-*
        ./Config -nointro
        make
        sudo make install
        sudo ln -s "$(pwd)" /home/runner/unrealircd

    - name: Compile and Install Module
      run: |
        cd /home/runner/unrealircd
        cp $GITHUB_WORKSPACE/m_ipinfo_whois/m_ipinfo_whois.c src/modules/third/m_ipinfo_whois.c
        cd /home/runner/unrealircd
        make
        sudo make install

    - name: Set up UnrealIRCd Configuration
      run: |
        echo 'loadmodule "third/m_ipinfo_whois";' >> /home/runner/unrealircd/conf/unrealircd.conf
        echo 'ipinfo_whois { apikey "YOUR_API_KEY"; };' >> /home/runner/unrealircd/conf/unrealircd.conf

    - name: Configtest UnrealIRCd
      run: |
        /home/runner/unrealircd/bin/unrealircd configtest

    - name: Rehash UnrealIRCd
      run: |
        /home/runner/unrealircd/bin/unrealircd rehash

    - name: Stop UnrealIRCd
      run: |
        /home/runner/unrealircd/bin/unrealircd stop
